class TaskNotFoundError(Exception):
    pass

class TaskAlreadyExists(Exception):
    pass